baseURL = "http://mabinouze.fr/"
languageCode = "fr-fr"
title = "Ma binouze"
enableInlineShortcodes = true
disableKinds = ['taxonomy', 'term', 'RSS']
theme = "mabinouze-v1"

[params]
icon = "ğŸº"
repository = "https://github.com/reveliant/mabinouze"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true
title = true